create table notice (id bigint not null auto_increment, create_time datetime(6), delete_at bigint not null, deleted bit, update_time datetime(6), content varchar(255), sub_title varchar(255), title varchar(255), weight bigint, create_user_id bigint, update_user_id bigint, image_id bigint, primary key (id)) engine=InnoDB;
create table sign_up_information (id bigint not null auto_increment, create_time datetime(6), delete_at bigint not null, deleted bit, update_time datetime(6), create_user_id bigint, update_user_id bigint, primary key (id)) engine=InnoDB;
create table volunteer (id bigint not null auto_increment, create_time datetime(6), delete_at bigint not null, deleted bit, update_time datetime(6), address varchar(255), be_star bit, birthday integer, education smallint, introduce varchar(255), sex bit, weight integer, create_user_id bigint, update_user_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
create table volunteer_volunteer_activities (volunteer_id bigint not null, volunteer_activities_id bigint not null) engine=InnoDB;
create table volunteer_activity (id bigint not null auto_increment, create_time datetime(6), delete_at bigint not null, deleted bit, update_time datetime(6), contact varchar(255), detail varchar(255), end_date integer, initiator varchar(255), name varchar(255), number_of_applicants bigint, number_of_audited_recruits bigint, number_of_planned_recruits bigint, place varchar(255), scale smallint, start_date integer, state smallint, create_user_id bigint, update_user_id bigint, picture_id bigint, primary key (id)) engine=InnoDB;
create table volunteer_activity_sign_up_information (volunteer_activity_id bigint not null, sign_up_information_id bigint not null) engine=InnoDB;
alter table volunteer_activity_sign_up_information add constraint UK_k1dcmbyjq7v9rbcd5dwvkhcup unique (sign_up_information_id);
alter table notice add constraint FK1mx58rq5uvryt770lsmx22tqn foreign key (create_user_id) references user (id);
alter table notice add constraint FK7crjx7xsyijk56x3ikeq6dfqx foreign key (update_user_id) references user (id);
alter table notice add constraint FKc6p19oqriuq7yg5sn3s8prhgk foreign key (image_id) references attachment (id);
alter table sign_up_information add constraint FKp6otwcm2lbspuqb1h44katngy foreign key (create_user_id) references user (id);
alter table sign_up_information add constraint FK3gl4sa3jxdqtygy5j2nv1dv86 foreign key (update_user_id) references user (id);
alter table volunteer add constraint FKal85q9p70w07bnt03dfcttjd5 foreign key (create_user_id) references user (id);
alter table volunteer add constraint FKmuleqifw8oewfh55m1jx1tlbf foreign key (update_user_id) references user (id);
alter table volunteer add constraint FK1jvgm2odpt824gq7jkwmkt2ny foreign key (user_id) references user (id);
alter table volunteer_volunteer_activities add constraint FKaonppca8q3jb3bkxxlgshx83n foreign key (volunteer_activities_id) references volunteer_activity (id);
alter table volunteer_volunteer_activities add constraint FKsiod7hhqdgxcmh2a0eoelyfrb foreign key (volunteer_id) references volunteer (id);
alter table volunteer_activity add constraint FK7bhca9j1jv8e9sju61v4p7o7i foreign key (create_user_id) references user (id);
alter table volunteer_activity add constraint FKeka81irgxql0906m385mnjtfj foreign key (update_user_id) references user (id);
alter table volunteer_activity add constraint FK5m12vml4i1xx66wux1sfceoar foreign key (picture_id) references attachment (id);
alter table volunteer_activity_sign_up_information add constraint FK20c76iuvmnniauv64v86hym83 foreign key (sign_up_information_id) references sign_up_information (id);
alter table volunteer_activity_sign_up_information add constraint FKgibq72s2j2s8bif5i0oat0sel foreign key (volunteer_activity_id) references volunteer_activity (id);