alter table community3d add column update_time datetime(6);
alter table community3d add column create_user_id bigint;
alter table community3d add column update_user_id bigint;
alter table crimed_type add column update_time datetime(6);
alter table crimed_type add column create_user_id bigint;
alter table crimed_type add column update_user_id bigint;
alter table cult add column update_time datetime(6);
alter table cult add column create_user_id bigint;
alter table cult add column update_user_id bigint;
alter table district add column update_time datetime(6);
alter table district add column create_user_id bigint;
alter table district add column update_user_id bigint;
create table duty (id bigint not null auto_increment, create_time datetime(6), delete_at bigint, deleted bit, update_time datetime(6), name varchar(255) not null, type_of_district varchar(255) not null, weight bigint not null, create_user_id bigint, update_user_id bigint, primary key (id)) engine=InnoDB;
alter table enterprise add column update_time datetime(6);
alter table enterprise add column create_user_id bigint;
alter table enterprise add column update_user_id bigint;
alter table house add column update_time datetime(6);
alter table house add column create_user_id bigint;
alter table house add column update_user_id bigint;
alter table job_type add column update_time datetime(6);
alter table job_type add column create_user_id bigint;
alter table job_type add column update_user_id bigint;
create table part_building (id bigint not null auto_increment, create_time datetime(6), delete_at bigint, deleted bit, update_time datetime(6), name varchar(255), wallah_name varchar(255), create_user_id bigint, update_user_id bigint, district_id bigint, duty_id bigint, user_id bigint, primary key (id)) engine=InnoDB;
alter table relationship add column update_time datetime(6);
alter table relationship add column create_user_id bigint;
alter table relationship add column update_user_id bigint;
alter table religious_belief add column update_time datetime(6);
alter table religious_belief add column create_user_id bigint;
alter table religious_belief add column update_user_id bigint;
alter table resident add column update_time datetime(6);
alter table resident add column be_vaccinated bit;
alter table resident add column not_vaccinated_reason varchar(255);
alter table resident add column vaccinated_place varchar(255);
alter table resident add column create_user_id bigint;
alter table resident add column update_user_id bigint;
alter table resident_relationships add column update_time datetime(6);
alter table resident_relationships add column create_user_id bigint;
alter table resident_relationships add column update_user_id bigint;
alter table role add column update_time datetime(6);
alter table role add column create_user_id bigint;
alter table role add column update_user_id bigint;
create table role_children (role_id bigint not null, children_id bigint not null) engine=InnoDB;
alter table skill add column update_time datetime(6);
alter table skill add column create_user_id bigint;
alter table skill add column update_user_id bigint;
alter table unit add column update_time datetime(6);
alter table unit add column create_user_id bigint;
alter table unit add column update_user_id bigint;
alter table user add column update_time datetime(6);
alter table user add column create_user_id bigint;
alter table user add column update_user_id bigint;
alter table village3d_model add column update_time datetime(6);
alter table village3d_model add column create_user_id bigint;
alter table village3d_model add column update_user_id bigint;
alter table resident drop index UK_8xqclsumlm6suao1tlixgu99i;
alter table resident add constraint UK6ru627d2q50d7o40kxw6hj83i unique (id_number, delete_at);
alter table community3d add constraint FKb24xvr47orppcew7n47kg17n0 foreign key (create_user_id) references user (id);
alter table community3d add constraint FK9b9qvvhot649aopuck6nkl015 foreign key (update_user_id) references user (id);
alter table crimed_type add constraint FKkrwal9w83tsx8ihho8vaaiv12 foreign key (create_user_id) references user (id);
alter table crimed_type add constraint FKjjs0i6ypdarmicme2x2mbr189 foreign key (update_user_id) references user (id);
alter table cult add constraint FK95cyjsh3lv9fdpx3n39wmg2gd foreign key (create_user_id) references user (id);
alter table cult add constraint FK1588we3vsy5mhjqtyilwrlyt7 foreign key (update_user_id) references user (id);
alter table district add constraint FK7se8hubshhc9jgyqiybryijd2 foreign key (create_user_id) references user (id);
alter table district add constraint FK8yff0m0s7erq2y6543hk1id5m foreign key (update_user_id) references user (id);
alter table duty add constraint FK9pihf54d65h8w041hjof3ulsh foreign key (create_user_id) references user (id);
alter table duty add constraint FK93ksptasf60hxjs1kf54arpcp foreign key (update_user_id) references user (id);
alter table enterprise add constraint FK8ufksj5bqvgw4bylwa2p70x03 foreign key (create_user_id) references user (id);
alter table enterprise add constraint FKobwr2etbr4ru2he87kq0mj716 foreign key (update_user_id) references user (id);
alter table house add constraint FKlsw1nqnq3kkdo8mihrqayq1gl foreign key (create_user_id) references user (id);
alter table house add constraint FK8r3ym26chld7oas0kluh97oyl foreign key (update_user_id) references user (id);
alter table job_type add constraint FKnnsnsc5lgsrmwotu44yuceu8w foreign key (create_user_id) references user (id);
alter table job_type add constraint FK4enr3v9bwwv3yymdtdbhrpw9f foreign key (update_user_id) references user (id);
alter table part_building add constraint FKdmbt64jtneic90rdepu3mddon foreign key (create_user_id) references user (id);
alter table part_building add constraint FKod1xtrkube6omgcx8bj4gmlao foreign key (update_user_id) references user (id);
alter table part_building add constraint FK8dmwnp21scqrjuvf60y8ylty7 foreign key (district_id) references district (id);
alter table part_building add constraint FKpl1uu3a80fak58e6i7iffiwkm foreign key (duty_id) references duty (id);
alter table part_building add constraint FKc1oqn83g2fhrw4b2dwddg2qqu foreign key (user_id) references user (id);
alter table relationship add constraint FK771flrwbrr01py0ysysj54xj6 foreign key (create_user_id) references user (id);
alter table relationship add constraint FKgsowufftfvo41nq6dyxtp0ws1 foreign key (update_user_id) references user (id);
alter table religious_belief add constraint FKmi3rouy9bx6xa7t3scfnjnmvw foreign key (create_user_id) references user (id);
alter table religious_belief add constraint FKsfwm1hcoer6sfnnrdvjdbi82v foreign key (update_user_id) references user (id);
alter table resident add constraint FKuw6tu5loggvwm6xfvo6ove7o foreign key (create_user_id) references user (id);
alter table resident add constraint FK3t7rmo58fig8i4t3lfsd9h1iw foreign key (update_user_id) references user (id);
alter table resident_relationships add constraint FKf2bau4urnvs76tcuseb3wndhs foreign key (create_user_id) references user (id);
alter table resident_relationships add constraint FKsowxet4eeotnrrk8wyeih5ac2 foreign key (update_user_id) references user (id);
alter table role add constraint FKm45ibgs8e9t1w7ljx2fursd94 foreign key (create_user_id) references user (id);
alter table role add constraint FK2wa1ndisv3kudjg1i9g55mpxc foreign key (update_user_id) references user (id);
alter table role_children add constraint FKm150rl16s7jqfpyti39paf13q foreign key (children_id) references role (id);
alter table role_children add constraint FK266eeikxn95ggv9l1drmgjva8 foreign key (role_id) references role (id);
alter table skill add constraint FKqyc95it29i1oaxlcb3q3bhux7 foreign key (create_user_id) references user (id);
alter table skill add constraint FKc7ymgpq0vlvfflvlcejgqfl16 foreign key (update_user_id) references user (id);
alter table unit add constraint FKc8yppfk4il2rwq47bnrpa68ag foreign key (create_user_id) references user (id);
alter table unit add constraint FKh8pse14uenn1fg8o1q1ckxudi foreign key (update_user_id) references user (id);
alter table user add constraint FKn1eo3hcou22xdhm9vmll8oivg foreign key (create_user_id) references user (id);
alter table user add constraint FKgs0sk67mcc6r48030sm9i7yk2 foreign key (update_user_id) references user (id);
alter table village3d_model add constraint FKoyxabvlh2j4v7cq92dguv5aso foreign key (create_user_id) references user (id);
alter table village3d_model add constraint FK1pa838tagw8c07vc8r28loccd foreign key (update_user_id) references user (id);
